// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWaFpRFHyG1Oi4WzI7FBgltDsaXwPqIQ',
    appId: '1:207941360530:android:4dbbc0b8406adf6f283f4b',
    messagingSenderId: '207941360530',
    projectId: 'to-do-app-cc3fb',
    storageBucket: 'to-do-app-cc3fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnUg5uSPoxGNh7kwRhRlh2d_8CjWti7RE',
    appId: '1:207941360530:ios:3be07b18a6da5a35283f4b',
    messagingSenderId: '207941360530',
    projectId: 'to-do-app-cc3fb',
    storageBucket: 'to-do-app-cc3fb.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw2Hc1aHusDRy_OXK0DTi9Ms_J22TZmb4',
    appId: '1:207941360530:web:63cf43c92e0885c9283f4b',
    messagingSenderId: '207941360530',
    projectId: 'to-do-app-cc3fb',
    authDomain: 'to-do-app-cc3fb.firebaseapp.com',
    storageBucket: 'to-do-app-cc3fb.firebasestorage.app',
    measurementId: 'G-6JXYX2MYBG',
  );

}